// This file is auto-generated by `amplify push` and committed to source control.
// Replace the placeholder values with your actual Amplify outputs after running `amplify push`.
const awsConfig = {
  Auth: {
    Cognito: {
      userPoolId: "us-east-1_XXXXXXXXX",          // from amplify push output
      userPoolClientId: "XXXXXXXXXXXXXXXXXXXXXXXXXX", // from amplify push output
      loginWith: { email: true },
    },
  },
  API: {
    REST: {
      EmailAnnotatorAPI: {
        endpoint: "https://XXXXXXXXXX.execute-api.us-east-1.amazonaws.com/prod",
        region: "us-east-1",
      },
    },
  },
  Storage: {
    S3: {
      bucket: "email-annotator-storage-XXXXXXXXXXXX",
      region: "us-east-1",
    },
  },
};

export default awsConfig;
